Add ability to store XMPP logs in files
XMPP-Interop-Testing/smack-sint-server-extensions pull request #15
Opened 2024-04-10 17:26 UTC by guusdk

This adds a new Smack debug logger that can be used to store XMPP traffic in distinct files per test.

To configure the logger, use these system properties when invoking the tests:

```
-Dsinttest.debugger="org.igniterealtime.smack.inttest.util.FileLogger$Factory"
-DlogDir=target/logs
```

The `logDir` property value is used to identify the directory in which the logs will be stored. The directory will be created if it doesn't already exist.

2024-04-10 17:37 UTC, guusdk commented
Using the new debug logger, the GitHub workflow that runs all checks in this repository will now expose the XMPP debug logs as an artifact of the GitHub Action.

2024-04-11 07:31 UTC, Fishbowler requested changes
One minor change, but otherwise, this is _awesome_
Observability++

2024-04-11 07:31 UTC, Fishbowler commented on src/main/java/org/igniterealtime/smack/inttest/util/FileLogger.java
> +            filename = "output";
Minor, but I'd like to change this to something more obvious, given it's the log for test framework setup and teardown.

```suggestion
            filename = "test_suite_orchestration";
```

2024-04-11 07:37 UTC, Fishbowler approved these changes

2024-04-11 07:37 UTC, merged