New tests for section "8.2 Moderator Use Cases: Kicking an Occupant" of XEP-0045: "Multi-User Chat"
XMPP-Interop-Testing/smack-sint-server-extensions pull request #27
Opened 2024-05-24 13:35 UTC by guusdk

2024-06-14 17:40 UTC, guusdk commented
Rebased

2024-06-23 20:09 UTC, Fishbowler requested changes
One minor typo to squash in, and a question about synchronicity, otherwise perfect.

2024-06-25 07:58 UTC, guusdk commented on src/main/java/org/jivesoftware/smackx/muc/MultiUserChatModeratorKickIntegrationTest.java
> +            threeSeesTwo.waitForResult(timeout);
I'm not exactly sure what you're asking. I believe that this code attempts to ensure that both 'one' and 'three' see the participant that's about to be kicked ('two'), prior to the kick to happen. I'm not actually sure if we need 'oneSeesThree'.

2024-06-25 19:28 UTC, Fishbowler commented on src/main/java/org/jivesoftware/smackx/muc/MultiUserChatModeratorKickIntegrationTest.java
> +            threeSeesTwo.waitForResult(timeout);
I was more talking about being "settled" to avoid flakes, but I'm not sure that's actually needed given the subsequent wait for the kick.

2024-06-25 19:28 UTC, Fishbowler approved these changes

2024-06-25 19:28 UTC, merged