Ad-hoc Command tests
XMPP-Interop-Testing/smack-sint-server-extensions pull request #4
Opened 2024-01-18 22:47 UTC by Fishbowler

For testing the Ad-hoc Commands in Openfire, many of which were added or edited in https://github.com/igniterealtime/Openfire/pull/2381

2024-02-06 20:02 UTC, Fishbowler commented on src/main/java/org/jivesoftware/smackx/commands/AdHocCommandIntegrationTest.java
> +            // TODO consider unmarking the user as being disabled, as deleting the user might not propagate.
@guusdk Wouldn't this be a bug in the server implementation?

2024-04-09 11:18 UTC, guusdk commented on src/main/java/org/jivesoftware/smackx/commands/AdHocCommandIntegrationTest.java
> +            // TODO consider unmarking the user as being disabled, as deleting the user might not propagate.
Yes, I think so.

2024-04-19 14:50 UTC, guusdk commented
Rebased

2024-04-19 15:11 UTC, guusdk commented
I've added the new Smack `@SpecificationReference` annotation (and friends). This makes it obvious that the current implementation tests both XEP-0133-specified commands, but also Openfire-specific ones. Maybe split those up over two distinct files?

2024-04-19 15:17 UTC, guusdk commented
I've noticed that these tests uses assertions from this source: `org.junit.Assert.*` - Most (all?) other tests use `org.junit.jupiter.api.Assertions.*` instead.

I'm not sure if there's a functional difference. One difference is the order of arguments being used in the various assertions. For consistency, lets use the same assertions everywhere.

2024-07-03 16:43 UTC, guusdk commented
Rebased.

2024-09-02 20:37 UTC, Fishbowler commented on src/main/java/org/jivesoftware/smackx/commands/AdHocCommandIntegrationTest.java
> +@SpecificationReference(document = "XEP-0133")
Needs a version

2024-09-21 13:54 UTC, Fishbowler commented
Rebased

2024-09-21 14:33 UTC, Fishbowler commented
Still to do:
 * Tests for s4.22
 * Tests for s4.24
 * Tests for s4.25
 * Tests for s4.26
 * Tests for s4.27
 * Tests for s4.28
 * Tests for s4.30
 * Tests for s4.31
 * Explicit `fail(...)` messaging for better output

2025-02-11 09:26 UTC, guusdk commented on pom.xml
> +                        <systemProperty>
Is this an artifact of your local development that wasn't supposed to be committed, or is this an intentional change?

2025-02-11 09:27 UTC, guusdk commented on pom.xml
> +        <repository>
I don't think a new dependency was added in this PR. Why the new repository definition?

2025-02-11 09:28 UTC, guusdk commented on src/main/java/org/jivesoftware/smackx/commands/AdHocCommandVendorSpecificIntegrationTest.java
> +    public AdHocCommandVendorSpecificIntegrationTest(SmackIntegrationTestEnvironment environment)
Should this throw a `TestNotPossible` based on the result of a `jabber:iq:version` check, to see what the make/model of the server under test is?

2025-03-16 17:32 UTC, Fishbowler commented on pom.xml
> +        <repository>
This was when the branch needed to grab a Smack snapshot, which no longer appears in the diff since the last rebase. Will revert this.

2025-03-16 17:33 UTC, Fishbowler commented on pom.xml
> +                        <systemProperty>
Correct. This was a commit to add a simple exec:java config. Will revert.

2025-03-16 22:44 UTC, Fishbowler commented on src/main/java/org/jivesoftware/smackx/commands/AdHocCommandVendorSpecificIntegrationTest.java
> +    public AdHocCommandVendorSpecificIntegrationTest(SmackIntegrationTestEnvironment environment)
Good idea!

2025-03-16 22:46 UTC, Fishbowler commented
This is a good chunk closer to Done. 

There's some errors I'd still like to tidy up in the Openfire vendor-specific tests.

2025-03-28 12:27 UTC, Fishbowler commented
@guusdk I think I've fixed all the things you rightly pointed out.

2025-04-03 14:48 UTC, guusdk requested changes
I have reviewed one test in detail: `testEndUserSession`. To avoid a lot of duplication, let's first see if we can apply the review comments to other tests.

2025-04-03 14:48 UTC, guusdk commented on src/main/java/org/igniterealtime/smack/inttest/xep0133/AdHocCommandIntegrationTest.java
> +    @SmackIntegrationTest(section = "4.5")
It would be best all tests to have a 'quote' (that describes what specific definition is subject of the test), and for all assertions to have a message (that is shown when the assertion fails). This is an example of a failing test that doesn't have such a quote, and not a message in the failed assertion either:

```
💀 The following 1 tests failed! 💀
• XEP-0133: Service Administration, Section 4.5
      "null"
  Failure reason  : expected: <true> but was: <false>
  Stanza log file : ./target/logs/AdHocCommandIntegrationTest.testEndUserSession (Normal).log
  Test class      : class org.igniterealtime.smack.inttest.xep0133.AdHocCommandIntegrationTest
  Test method     : testEndUserSession
  ```
  
  It's next to impossible for anyone to explain why this test is failing.

2025-04-03 14:48 UTC, guusdk commented on src/main/java/org/igniterealtime/smack/inttest/xep0133/AdHocCommandIntegrationTest.java
> +    public void testEndUserSession() throws Exception {
The XEP reads:

> If the JID is of the form <user@host>, the service MUST end all of the user's sessions; if the JID is of the form <user@host/resource>, the service MUST end only the session associated with that resource.

Shouldn't this be _two_ tests, instead of one (to match each of the MUST definitions)?

2025-04-03 14:48 UTC, guusdk commented on src/main/java/org/igniterealtime/smack/inttest/xep0133/AdHocCommandIntegrationTest.java
> +            assertTrue(jids.contains(userConnection.getUser().asEntityBareJidString()));
I don't like using an assertion to check if the test fixture has been set up correctly. If the assertion fails, it suggests that the feature-under-test is failing. That's not the case here. Maybe a `throws new TestNotPossible()` (with a descriptive message) is more appropriate.

Additionally, using GET_LIST_OF_ACTIVE_USERS for this purpose puts a strict requirement that its implementation is giving a truly 'live' representation. I can image that this isn't always the case. It would be better to somehow wait (with a timeout) for the user to become part of this list.

Do we need to use this list at all? We only need to detect that the user is kicked, right? Can't we determine that based on some kind of event listener on the connection that we're kicking?

2025-04-03 14:48 UTC, guusdk commented on src/main/java/org/igniterealtime/smack/inttest/xep0133/AdHocCommandIntegrationTest.java
> +            result = executeCommandWithArgs(GET_LIST_OF_ACTIVE_USERS, adminConnection.getUser().asEntityBareJid(),
I would prefer not using another adhoc command to assert that this test is correct. Can't we simply look at the connection state of `userConnection`?

To avoid race conditions, it probably is best to introduce some kind of event listener that waits for a short time to see if the connection is killed (instead of depending on the fact that the very first snapshot of the list of active users is immediately up-to-date).

2025-04-03 15:05 UTC, guusdk commented on src/main/java/org/igniterealtime/smack/inttest/xep0133/AdHocCommandIntegrationTest.java
> +            assertNoteType(AdHocCommandNote.Type.info, result);
Should we assert the 'note' element? It is not present in any of the [XEP-0133](https://xmpp.org/extensions/xep-0133.html) examples (or mentioned anywhere in its text). My reading of [XEP-0050](https://xmpp.org/extensions/xep-0050.html) is that they're optional. If they're optional, we probably shouldn't test them. If we do test them, then the assertion should have a message.

2025-04-03 15:20 UTC, guusdk commented
I have added [a commit that addresses much of my review points](https://github.com/XMPP-Interop-Testing/smack-sint-server-extensions/pull/4/commits/9d84f58f528de2880ea41e4b4435586ceb06b26d) for the End User Session command. Let's discuss if this is the right approach, after which I can apply similar changes to other commands.

2025-04-10 19:22 UTC, guusdk commented on src/main/java/org/igniterealtime/smack/inttest/xep0133/AdHocCommandIntegrationTest.java
> +    @SmackIntegrationTest(section = "4.5")
I have committed changes that address this in all tests that are part of this PR.

2025-04-10 19:23 UTC, guusdk commented on src/main/java/org/igniterealtime/smack/inttest/xep0133/AdHocCommandIntegrationTest.java
> +    public void testEndUserSession() throws Exception {
I have committed additional tests.

2025-04-10 19:27 UTC, guusdk commented on src/main/java/org/igniterealtime/smack/inttest/xep0133/AdHocCommandIntegrationTest.java
> +            assertNoteType(AdHocCommandNote.Type.info, result);
I have committed a change where there are two new assertions, assertCommandCompletedSuccessfully and assertCommandFailed. They no longer solely depend on there being a 'note'.

2025-04-10 19:28 UTC, guusdk commented on src/main/java/org/igniterealtime/smack/inttest/xep0133/AdHocCommandIntegrationTest.java
> +            result = executeCommandWithArgs(GET_LIST_OF_ACTIVE_USERS, adminConnection.getUser().asEntityBareJid(),
Where possible, I switched using adhoc commands to assert a certain state with something that uses an event listener.

2025-04-10 19:29 UTC, guusdk approved these changes
I believe that I have now addressed all of the issues that I raised earlier. This amounted to more work than anticipated. It would be good for @Fishbowler to review my work again, given the large amount of changes.

2025-04-21 20:53 UTC, Fishbowler commented
Thanks Guus! I've been through all of these changes, commit by commit, and they're all ace. There was a lot of cruft from when this was intended for Openfire only that I was blind to.

2025-04-21 20:53 UTC, merged